import:
  - display/desktop/xsetroot
# - display/desktop/feh
  - display/color/nikki
  - display/notice
  - display/client
  - display/tags
  - display/status/music/mpd
  - display/status/volume/amixer
  - display/status/storage/dfnikki
  - display/status/system/loadavg
  - display/status/time
  - control/mouse
  - control/keyboard/nikki
  - control/keyboard/nikki/arrange_by_number
  - control/keyboard/nikki/arrange
  - control/keyboard/nikki/client
  - control/keyboard/nikki/detach
  - control/keyboard/nikki/focus_by_letter
  - control/keyboard/nikki/focus_by_number
  - control/keyboard/nikki/focus
  - control/keyboard/nikki/group
  - control/keyboard/nikki/launch
  - control/keyboard/nikki/layout_by_number
  - control/keyboard/nikki/layout
  - control/keyboard/nikki/menu
  - control/keyboard/nikki/move_by_number
  - control/keyboard/nikki/move
  - control/keyboard/nikki/swap_by_number
  - control/keyboard/nikki/swap
  - control/keyboard/nikki/zoom

prefer:
  terminal: urxvt
  browser: firefox
  editor: gvim
  filer: thunar

display:
  bar: bottom
  font: "-*-fixed-medium-r-*-*-11-*-*-*-*-*-*-*"
  border: 1

  column:
    mode: default
    rule: |
      /.*/ -> 60+40

  client:
    - /\b(xconsole|alsamixer|XMMS|Sonata)\b/ : 1
    - /Applet Viewer/ : '~'
    - /^pidgin:|:WeeChat\b/ : chat
