import:
  - display/desktop/xsetroot
  - display/desktop/feh
  - display/color/zenburn
  - display/notice
  - display/client
  - display/tags
  - display/status/music/mpd
  - display/status/volume/amixer
  - display/status/storage/df
  - display/status/system/loadavg
  - display/status/time
  - control/mouse
  - control/keyboard/dvorak
  - control/keyboard/dvorak/arrange_by_number
  - control/keyboard/dvorak/arrange
  - control/keyboard/dvorak/client
  - control/keyboard/dvorak/detach
  - control/keyboard/dvorak/focus_by_letter
  - control/keyboard/dvorak/focus_by_number
  - control/keyboard/dvorak/focus
  - control/keyboard/dvorak/group
  - control/keyboard/dvorak/launch
  - control/keyboard/dvorak/layout_by_number
  - control/keyboard/dvorak/layout
  - control/keyboard/dvorak/menu
  - control/keyboard/dvorak/move_by_number
  - control/keyboard/dvorak/move
  - control/keyboard/dvorak/swap_by_number
  - control/keyboard/dvorak/swap
  - control/keyboard/dvorak/zoom

prefer:
  terminal: urxvt
  browser: chromium
  editor: gvim
  filer: thunar

display:
  bar: bottom
  font: "-*-fixed-medium-r-*-*-18-*-*-*-*-*-*-*"
  border: 5
  column:
    mode: default
    rule: |
      /.*/ -> 50+50
  client:
    - /\b(xconsole|alsamixer|XMMS|Sonata)\b/  : 1
    - /^chromium:Chromium:Chromium Options$/  : '~'
    - /^chromium:Chromium:Task Manager/       : '~'
    - /Save a Bookmark on Delicious/          : '~'
    - /^xmag/                                 : '~'
    - /Applet Viewer/                         : '~'
    - /^pidgin:|:WeeChat\b/                   : chat
    - /Meld$/                                 : merge
