import:
  - display/desktop/xsetroot
# - display/desktop/feh

  - display/color/nikki

  - display/notice
  - display/client
  - display/tags

  - display/status/spacer
  - display/status/arch/packages
  - display/status/music/mpd
  - display/status/volume/amixer
  - display/status/system/loadavg
  - display/status/power/acpi
  - display/status/time

  - control/mouse
  - control/keyboard/nikki
  - control/keyboard/nikki/arrange_by_number
  - control/keyboard/nikki/arrange
  - control/keyboard/nikki/client
  - control/keyboard/nikki/detach
  - control/keyboard/nikki/focus_by_letter
  - control/keyboard/nikki/focus_by_number
  - control/keyboard/nikki/focus
  - control/keyboard/nikki/group
  - control/keyboard/nikki/launch
  - control/keyboard/nikki/layout_by_number
  - control/keyboard/nikki/layout
  - control/keyboard/nikki/menu
  - control/keyboard/nikki/move_by_number
  - control/keyboard/nikki/move
  - control/keyboard/nikki/swap_by_number
  - control/keyboard/nikki/swap
  - control/keyboard/nikki/zoom
  - control/keyboard/nikki/resize

prefer:
  terminal: urxvt
  browser: firefox
  editor: gvim
  filer: thunar
  tray: witray
  music: urxvt -e ncmpcpp

display:
  bar: bottom
  font: "xft:DejaVu Sans Mono-11:dpi=81"
  border: 2

  column:
    mode: default
    rule: |
      /gimp/ -> 17+80+10
      /.*/ -> 62+38

  client:
    - /witray/ : '/./'
    - /Applet Viewer/ : '~'
    - /gimp.*/ : 'gimp'

  status:
    acpi:
      battery: BAT

script:
  - after: |
      launch CONFIG['prefer']['tray']
