script:
  - after: |
      action 'rehash'

control:
  action:

    reload: |
      # reload this wmii configuration
      Wmiirc::Loader.reload

    rehash: |
      # scan for available programs and actions
      @programs = find_programs(ENV['PATH'].squeeze(':').split(':'))

    clear: |
      # kill all currently open clients

      # firefox's restore session feature does not
      # work unless the whole process is killed.
      system 'killall firefox firefox-bin thunderbird thunderbird-bin'
      system 'killall chromium-browser'

      # gnome-panel refuses to die by any other means
      system 'killall -s TERM gnome-panel'

      # witray too. :-)
      system 'killall witray'

      Thread.pass until clients.each do |c|
        begin
          c.focus # XXX: client must be on current view in order to be killed
          c.kill
        rescue
          # ignore
        end
      end.empty?

    kill: |
      # kill the window manager only; do not touch the clients!
      fs.ctl.write 'quit'

    quit: |
      # kill both clients and window manager
      action 'clear'
      action 'kill'
